### ISSUE TITLE
Search bar styling not correct in safari

### ISSUE THREAD

**Issue by pebcarecom** [ehelse/finnkode#24]
Hi Sara, 
We did some testing last week and found that the search bar isn't looking correct in Safari - it's to narrow and the corners aren't rounded.
![Screenshot 2019-07-09 at 09 07 23](https://user-images.githubusercontent.com/52452256/60866753-71e98900-a229-11e9-87ac-b223bab3be41.png)

**Comment by sjbrodwall** [comment]
![ea51b52235d18d535f5c211de0c52253](https://user-images.githubusercontent.com/357680/61485888-86a0ec00-a9a2-11e9-8586-325225361f59.png)

Looks like it works now based on BrowserShots--test again?
