### ISSUE TITLE
Sorting of search results

### ISSUE THREAD

**Issue by sjbrodwall** [ehelse/finnkode#28]

**Comment by sjbrodwall** [comment]
http://carecom.finnkode.tilgjengeligforalle.no/site/search-global-results.html

**Comment by kmh-carecom** [comment]
Sorting should both be ascending and descending. To me it looks like that is not support i you design?

**Comment by sjbrodwall** [comment]
Most of the net shops that do this just have the type of sort, and every time the user chooses to short it sorts in the opposite direction.  (See f.eks. https://www.komplett.no/category/21064/mobiler-klokker/mobiltelefoner).  I'll add the stigende/synkende options, however.

**Comment by kmh-carecom** [comment]
That makes sense. Didn't got that that was the way it was suppose to work :)
How the design should be is up to you and not me, so if you want to stick with the original design that is ok with me.

**Comment by sjbrodwall** [comment]
Let's keep it simple to start with and leave it as-is. I figure it's NBT to implement navn synkende/kode synkende (evt. relevans stigende :D) if these are requested. 

Hopefully this will be user-tested in the pilot, my theory is that it doesn't provide much value to the user to sort results on name or code alphabetically.  Especially if we go for infinite scroll (which has many issues itself), how is the user to navigate to anything other than A or Å?
